"""empty message

Revision ID: fe4f8e35af8e
Revises: 5b33b013378c
Create Date: 2024-05-10 04:58:38.115269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe4f8e35af8e'
down_revision = '5b33b013378c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('upvotes')
        batch_op.drop_column('downvotes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('downvotes', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('upvotes', sa.INTEGER(), nullable=True))

    op.drop_table('like')
    # ### end Alembic commands ###
